# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=root" "noatime" "compress=zstd"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=home" "noatime" "compress=zstd"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=nix" "noatime" "compress=zstd"];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=tmp" "noatime" "compress=zstd"];
  };

  fileSystems."/opt" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=opt" "noatime" "compress=zstd"];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=srv" "noatime" "compress=zstd"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/1be8935d-8bbe-4d3d-892d-443f85daa612";
    fsType = "btrfs";
    options = ["subvol=var" "nodatacow"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7928-CF1A";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/66ccfc6e-a1b7-40d8-b4e0-9e1ed758fe7b";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
